import org.apache.hadoop.io.SecureIOUtils.AlreadyExistsException;
public class FunctionUse16156 {
public void funcUse() {
AlreadyExistsException alreadyexistsexception = new AlreadyExistsException();
}
}